### ISSUE TITLE
Seccion Equipo

### ISSUE THREAD

**Issue by bossiernesto** [uqbar-project/uqbar-landing#12]
Revisar esta seccion y ver si queda la seccion en la landing o en una aparte, actualmente tenemos esto de la siguiente manera en el antiguo sitio  http://www.uqbar-project.org/team-and-contacts

**Comment by lspigariol** [comment]
La Lista de integrantes esta re desactualizada, podemos preguntar en la lista quien quiere estar y con qué info.

la parte de newsletter se puede sacar
las listas por proyectos, puede ir en cada proyecto (activo)

La lista de mails tambien se puede sacar, es interna. 
Habia otra de anuncios que no sé en qué situacion está
no se si tenemos un mail oficial que alguien lea.

lo que si conviene agregar es
https://www.facebook.com/fundacionuqbar/
https://www.instagram.com/fundacionuqbar/
https://twitter.com/UqbarProject
