### ISSUE TITLE
Seccion de FAQ

### ISSUE THREAD

**Issue by bossiernesto** [uqbar-project/uqbar-landing#17]
Ver de migrar la seccion de FAQ que teniamos en la vieja página a la nueva

http://www.uqbar-project.org/faq

**Comment by lspigariol** [comment]
esta seccion podria no estar, al menos en una primera etapa. Lo mas interesante que es el como participar, puede ir en quiernes somos / contacto

**Comment by bossiernesto** [comment]
Ok, estoy enviando lo que tenemos en el PR #30, avisenme si saco el resto, igualmente en la pagina figura en ingles
