### ISSUE TITLE
Sección eventos

### ISSUE THREAD

**Issue by asanzo** [uqbar-project/uqbar-landing#33]
En particular, con la info de la jornada del 16.

**Comment by PalumboN** [comment]
Done: http://www.uqbar.org/eventos

**Comment by asanzo** [comment]
Algo extraño: esa url no me la tomó, tuve q sacarle el www.

Abz!

**Comment by PalumboN** [comment]
Le tuviste que sacar el www. o el /eventos? https://github.com/uqbar-project/uqbar-landing/issues/35

**Comment by asanzo** [comment]
Lo hice desde el celular, no recuerdo qué hice. Sigo en el otro issue.
