### ISSUE TITLE
/eventos no anda

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/uqbar-landing#35]
Si entrás directamente a `http://www.uqbar.org/eventos` tira 404, pero si se navega desde la landing anda (esto es porque esa url es una mentira de `react-router`). 
Habría que hacer alguna magia para que redirija correctamente.

**Comment by PalumboN** [comment]
Creo que esto sucede por un problema en el servidor, por en localhost funciona y redirige.
@tesonep, puede ser que el server esté tratando de resolver el `/eventos` y por eso tire 404? Se podrá hacer que siempre (`http://www.uqbar.org/*`) devuelva el mismo `index.html` para que el cliente se encargue del ruteo?

**Comment by bossiernesto** [comment]
En realidad es un tema del router de react y habria que cambiar ese link del menu por `https://www.uqbar.org/#/eventos` . Esto tiene que ve un poco por como funciona `react-router`, ya que es un ruteo del lado del cliente en vez del lado del servidor.

Hay dos fases en el request, el primero es el que hace el cliente contra el servidor para obtener todo el codigo del JS de react, junto con el router. El tema es que en esta segunda fase una vez que se carga la pagina, si vas a la parte de eventos esto funcionaria, porque en realidad el ruteo lo hace del lado del cliente y no del servidor, mediante el History API (https://developer.mozilla.org/en-US/docs/Web/API/History_API), y como la parte de eventos no necesita hacer ningun request a servidor entonces solo tiene que renderizar el html correspondiente. Al no existir un request propiamente dicho al servidor para obtener la parte de eventos, todo se hace del lado del cliente.

Como se arreglaria esto?

Bueno habria que usar hash history (https://github.com/jintoppy/react-training/blob/master/basic/node_modules/react-router/docs/guides/Histories.md#hashhistory) para que lo que viene despues del hash no se envie al servidor, y que en realidad, lo procese el router del lado del cliente. Entonces `http://www.uqbar.org/` lo recibiria el servidor mientras que `#/eventos` lo procesaria el router una vez que esta el codigo de JS del lado del cliente

**Comment by PalumboN** [comment]
Done! :+1:
