### ISSUE TITLE
Menu Principal - Decidir la navegacion

### ISSUE THREAD

**Issue by bossiernesto** [uqbar-project/uqbar-landing#4]

**Comment by lspigariol** [comment]
en el menu principal
sacaria FAQ
agregaria Actividades 
Quienes Somos en vez de contacto

en inicio puede quedar destacado: 
- un proyecto (wollok)
- una actividad reciente o proxima (ahora podria ser el ultimo taller de wollok, en un tiempo subir otras
- una foto general (la del wisit que esta en el perfil de face)
