### ISSUE TITLE
Agregar proyectos

### ISSUE THREAD

**Issue by bossiernesto** [uqbar-project/uqbar-landing#8]
- Cambiar el nombre
- Actualizar iconos 
- Revisar contenido y texto
-Definir si se pasa a renombrarlo como actividades que deberian contener:
   - Proyectos
   - Eventos

**Comment by lspigariol** [comment]
Yo le dejaría proyectos

destacaria primero a
wollok
ozono
arena

agregar yanapiri


y como otros o anteriores los demas.

mumuki podria estar bajo un titulo "proyectos amigos" o similar.

**Comment by PalumboN** [comment]
Actualmente faltaría agregar [Ozono](http://ozono.uqbar-project.org/) (que no sé si alguien lo sigue manteniendo --> https://github.com/uqbar-project/uqbar-landing/issues/14)

> mumuki podria estar bajo un titulo "proyectos amigos" o similar.

Me gusta esto, estaría bueno ver dónde -> https://github.com/uqbar-project/uqbar-landing/issues/43

**Comment by PalumboN** [comment]
También habría que agregar el labo de funciones: https://github.com/uqbar-project/function-laboratory

**Comment by nscarcella** [comment]
Buenas, comento por acá como me dijo @PalumboN :

Estaría bueno linkear al contenido que generamos del taller de lenguajes (calculo que el mejor punto de entrada sería https://github.com/uqbar-taller-de-lenguajes/taller-2017/wiki).

Hay mucho contenido escrito en español y podría servir para futuras iteraciones, pero si no está en la página es difícil de encontrar.

**Comment by PalumboN** [comment]
Esto ya estaría fixeado en https://github.com/uqbar-project/uqbar-landing/pull/49

@nscarcella faltaría una imagen para el taller de lenguajes. Por ahora puse la de uqbar, se podría armar algo similar a la de la Wiki o quizá se te ocurra algo más piola. Busqué rápidamente en google pero no encontré ninguna que me convenciera.

**Comment by asanzo** [comment]
La imagen del taller quedó así:

![Selección_999(570)](https://user-images.githubusercontent.com/5421992/95359301-5c399800-08a0-11eb-9a42-ac3357bea9e8.png)
