### ISSUE TITLE
Link de discord roto

### ISSUE THREAD

**Issue by Fluzko** [uqbar-project/uqbar-landing#87]
Buenas, recién intente unirme al discord mediante el link que tienen la web. El mismo me arroja un error, supongo, de caducidad:
![image](https://user-images.githubusercontent.com/37568902/202828595-042f174c-b320-4189-b6ec-a9960b38690b.png)
El link que figura actualmente es: https://discord.com/invite/5wVEwse
[En este link](https://support.discord.com/hc/en-us/articles/208866998-Invites-101), de la documentación oficial de Discord, se puede ver como crear un enlace permanente para que no vuelva a pasar a futuro

**Comment by asanzo** [comment]
Gracias, Facundo!! El nuevo es este: https://discord.gg/pKGpEPjYnC (para quien quiera hacerse el PR)

**Comment by PalumboN** [comment]
El link ya está arreglado, tuvimos un problema con el deploy. Gracias a ambos :)
